django_test/TestProject1/Polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.details, name='details'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/votes/', views.votes, name='votes'),
]

django_test/TestProject1/TestProject1/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import saludin

urlpatterns = [
    path('polls/', include('Polls.urls')),
    path('admin/', admin.site.urls),
    path('saludin/', saludin)
]

django_test/TestProject1/Polls/models.py
import datetime
from django.utils import timezone
from django.db import models 


class Question(models.Model):
    text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')

    def recently_published(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=6)

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('choice_text', max_length=200)
    votes = models.IntegerField('votos!', default=0)

    def __str__(self):
        return self.choice_text

django_test/TestProject1/Polls/views.py
from django.shortcuts import (render, get_object_or_404)
from django.http import (Http404, HttpResponse)
from django.template import loader

from .models import Question


def index(request):
    list_of_questions = Question.objects.order_by('-pub_date')[:5]
    context = {'list_of_questions': list_of_questions}
    return render(request, 'polls/index-new.html', context)


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})


def results(request, question_id):
    response = 'You are looking at the results for question %s'
    return HttpResponse(response % question_id)


def votes(request, question_id):
    voting = 'You are looking at the votes on question %s'
    return HttpResponse(voting % question_id)

django_test/TestProject1/TestProject1/views.py
from django.http import HttpResponse


def saludin(request):
    return HttpResponse("holis uwu")

django_test/TestProject1/Polls/templates/polls/details.html
<!DOCTYPE html>
<html lang="en" style="
    font-size: 22px;
    border: double white 33px;">
<head>
    <meta charset="UTF-8">
    <title>Question :: {{question.id}} :: Details</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'stylesheets/details-styles.css' %}">
</head>
<body style="background-color: rgba(150, 110, 440, 0.3);">
    <h1 style="
        text-align: center;">
        You are looking at the details of question {{question.id}}
    </h1>

    <form action="{% url 'polls:votes' question.id %}" method="post">
    {% csrf_token %}
        <fieldset>
            <legend style="text-align: center;">
                <h1>Question:: <i>"{{question}}"</i></h1>
            </legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}

            <div id="background">
            {% if question.choice_set.count == 0 %}
                <p class="ps">There are no choices available at the moment.</p>
                {% elif question.choice_set.count > 1 %}
                <h3 style="text-align: center;">Which is the correct answer?</h3>
                {% for choice in question.choice_set.all %}
                <input class="input"
                       type="checkbox"
                       value="{{ choice.id }}"
                       id="choice{{ forloop.counter }}">
                <label for="choice{{ forloop.counter }}"> {{ choice }}</label><br>
                {% endfor %}
            {% endif %}
            </div>
            <div id="test-div"></div>
            <input type="button" value="vote" class="votebutton">
            <h2 id="pub_date">Question publication date: {{question.pub_date}}</h2>
        </fieldset>
    </form>


    <footer>
        <p class="ps">This project is part of (insert ONG) Program to instill inspiration
            to make and respond to the most important questions and matters
            among students from anywhere in the world.</p>

    </footer>
</body>
</html>

django_test/TestProject1/Polls/templates/polls/index-new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questions Index!</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'stylesheets/index-styles.css' %}">
</head>
<body>
    <h1><i>Welcome to index.</i></h1>
    {% if list_of_questions %}
        <ul>
        {% for question in list_of_questions %}
            <li>
                <a href="{% url 'polls:details' question.id %}">
                    {{ question.text }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</body>
</html>